-- ============================================================
-- 060_quotation_atomic_save.sql
--
-- save_quotation_items() wraps delete-existing-items, insert-new-items,
-- and update-quotation-totals in ONE Postgres function, so all three
-- writes commit or roll back together. Fixes a real data-loss window
-- found in Task 5's review: three separate supabase-js calls (no
-- client-side transaction support) meant an insert failing after the
-- delete succeeded left a quotation with zero items but a stale
-- non-zero total, with no recovery path.
--
-- p_items is a jsonb array -- supabase-js's .rpc() accepts a plain JS
-- array/object for a jsonb parameter directly. Each element's own `id`
-- must be a real UUID generated by the CALLER (crypto.randomUUID()
-- client-side -- see the Task 13 fix), not a placeholder string, so a
-- child item's parent_item_id can reference a sibling item in the SAME
-- batch by its real id before either row exists in the table yet.
--
-- This function is only ever called via supabaseAdmin() (the
-- service-role client -- see src/lib/quotations/crud.ts), where
-- auth.uid() is always NULL. An in-function auth.uid() check would
-- therefore unconditionally fail every legitimate call. Authorization
-- happens one layer up, in the Next.js API route that calls this
-- function (Task 6), which uses the RLS-scoped request-context client
-- to verify the caller can see the quotation before ever reaching this
-- admin-client-only function. This mirrors the codebase's own
-- established convention for every other admin-client-only RPC -- see
-- increment_automation_execution_count in
-- 007_automations_increment_counter.sql: no in-function auth check,
-- REVOKE from anon/authenticated, GRANT to service_role only.
--
-- account_id is derived from the quotation row itself, not trusted
-- verbatim from the caller-supplied p_account_id argument -- a wrong
-- or malicious p_account_id must not be able to tag quotation_items
-- rows with the wrong tenant.
--
-- Idempotent -- safe to run multiple times.
-- ============================================================

CREATE OR REPLACE FUNCTION save_quotation_items(
  p_quotation_id uuid,
  p_account_id uuid,
  p_items jsonb,
  p_subtotal numeric,
  p_discount_amount numeric,
  p_total numeric
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_account_id uuid;
BEGIN
  SELECT q.account_id INTO v_account_id
  FROM quotations q
  WHERE q.id = p_quotation_id;

  IF v_account_id IS NULL THEN
    RAISE EXCEPTION 'Quotation not found' USING ERRCODE = 'P0002';
  END IF;

  DELETE FROM quotation_items WHERE quotation_id = p_quotation_id;

  INSERT INTO quotation_items (
    id, quotation_id, account_id, parent_item_id, product_id, position,
    item_type, kind, item_code, description, description_ar,
    size_w, size_h, qty, unit_price, discount_type, discount_value, line_total
  )
  SELECT
    (elem->>'id')::uuid,
    p_quotation_id,
    v_account_id,
    NULLIF(elem->>'parent_item_id', '')::uuid,
    NULLIF(elem->>'product_id', '')::uuid,
    (elem->>'position')::integer,
    elem->>'item_type',
    elem->>'kind',
    elem->>'item_code',
    elem->>'description',
    elem->>'description_ar',
    (elem->>'size_w')::numeric,
    (elem->>'size_h')::numeric,
    COALESCE((elem->>'qty')::numeric, 1),
    (elem->>'unit_price')::numeric,
    elem->>'discount_type',
    (elem->>'discount_value')::numeric,
    COALESCE((elem->>'line_total')::numeric, 0)
  FROM jsonb_array_elements(p_items) AS elem;

  UPDATE quotations
  SET subtotal = p_subtotal, discount_amount = p_discount_amount, total = p_total
  WHERE id = p_quotation_id;
END;
$$;

ALTER FUNCTION save_quotation_items(uuid, uuid, jsonb, numeric, numeric, numeric) OWNER TO postgres;

-- Only the service role needs to call this (crud.ts uses
-- supabaseAdmin()). Explicitly lock anon / authenticated out --
-- matches increment_automation_execution_count's convention exactly.
REVOKE ALL ON FUNCTION save_quotation_items(uuid, uuid, jsonb, numeric, numeric, numeric) FROM PUBLIC;
REVOKE ALL ON FUNCTION save_quotation_items(uuid, uuid, jsonb, numeric, numeric, numeric) FROM anon;
REVOKE ALL ON FUNCTION save_quotation_items(uuid, uuid, jsonb, numeric, numeric, numeric) FROM authenticated;
GRANT EXECUTE ON FUNCTION save_quotation_items(uuid, uuid, jsonb, numeric, numeric, numeric) TO service_role;
